### ISSUE TITLE
Run tests on CI

### ISSUE THREAD

**Issue by Navidda** [rwth-acis/mobsos-surveys#25]
### Current State
The Travis CI has recently stopped working and therefore tests are not run automatically on CI.

### Desired State
Make tests run on CI

### Possible Solutions
There are two possible solutions:
1. As the travis-ci.org has moved to travis-ci.com, we can setup the project on travis-ci.com
2. Use github actions and add a testing stage on github ci.

**Comment by AlexanderNeumann** [comment]
I migrated our old setup from travis-ci.org to travis-ci.com. 
We have to take care what is possible with the free plan and we do not run out of ressources. 

https://travis-ci.com/github/rwth-acis/mobsos-surveys

I think having github actions as a backup would be a good idea
