### ISSUE TITLE
Mensa Survey

### ISSUE THREAD

**Issue by Navidda** [rwth-acis/mobsos-surveys#30]
Create a survey for Mensa

**Comment by Navidda** [comment]
Dear ${USER.NAME}! For assessing the usability of Mensabot please fill out the following questionnaire. Completion will take approximately 5 minutes.

1. Does Mensabot provide the precise information you need?
2. Does the information content meet your needs?
3. Does Mensabot provide reports that seem to be just about exactly what you need?
4. Does Mensabot provide sufficient information?
5. Do you find the output relevant?
6. Is Mensabot accurate?
7. Are you satisfied with the accuracy of Mensabot?
8. Do you feel the output of Mensabot is reliable?
9. Do you feel Mensabot is dependable?
10. Do you think the output of Mensabot is presented in a useful format?
11. Is the information clear?
12. Are you happy with the layout of the output?
13. Is the output easy to understand?
14. Is Mensabot user friendly?
15. Is Mensabot easy to use?
16. Is Mensabot efficient?
17. Do you get the information you need in time?
18. Does Mensabot provide up-to-date information?

**Comment by Navidda** [comment]
### 1. General Information  
- 1.1.  What is the degree of the program that you are enrolled in?
	- Master
	- Bachelor 
- 1.2.  In which semester are you currently?
	- 1st
	- 2nd
	- 3rd
	- 4th
	- 5+
- 1.3. Which one do you identify yourself?
	- Male
	- Female
	- Diverse
- 1.4. Which Mensa do you use more often?
	1. Aachen, Forum Cafete
	2. Aachen, Bistro Templergraben 
	3. Aachen, Mensa Ahorn
	4. Aachen, Mensa Vita  
	5. Aachen, Mensa Bayernallee
	6. Aachen, Mensa EUPS
	7. Aachen, Gastro Goethe
	8. Aachen, Mensa Academica
- 1.5. How often do you eat Mensa food?
	- Never
	- A few times a year
	- A few times a month
	- A few times a week
	- Every day

### 2. Mensa in Corona Time
- 2.1. Have you used the Mensa during its to-go operation?
	- No
	- Just a few times (<=5)
	- Yes (>5)
- 2.2. How were you satisfied with Mensa food during its to-go operation?
	- Not at all
	- to some extent
	- Fully satisfied
- 2.3. Are you happy that you can sit in the Mensa again?
	- No, that was not a good decision
	- Indifferent
	- Yes! I was waiting for this
- 2.4. Do you like to eat inside the Canteen?
	- No, I don't use Mensa so often
	- No, I prefer not to sit in because of my Corona concerns
	- No, I prefer not to sit in for other reasons
	- Yes! That is great!
- 2.5. Do you think the Covid protocols are observed in the Mensa by customers and staff (Face mask, distance rule, ...)?
	- Completely Disagree
	- Partly agree
	- Completely Agree
- 2.6. Do you think the Canteen area is hygenic in terms of air circulation, availability of disinfectant, ...?
	- Completely Disagree
	- Partly agree
	- Completely Agree

### 3. Mensa Quality
- 3.1. How do you rate the Mensa food?
	- Perfect, Average, Terrible
- 3.2. How do you rate the value for money of the food you buy from Mensa?
	- Perfect, Average, Terrible
- 3.3. What is your favourite option in Mensa menu?
	- Vegetarian
	- Classic
	- Pizza
	- Wok
	- Burger
- 3.4. Are you satisfied with the payment method provided?
	- Not at all
	- to some extent
	- Fully satisfied
- 3.5. What would attract you to eat regularly in the canteen? (Check all that apply)
	- Price compared to competitors
	- Not having to make a packed lunch
	- The choice of food
	- Eating a hot meal
	- Healthy options
	- Speed of service
	- other (please specify)
- 3.6. What would put you off eating in the canteen (Check all that apply)
	- Queues are too long
	- Don’t like the choice of food
	- Too expensive
	- My preferred choice(s) of food are sold out too early
	- Other (give details)

### 4. MensaBot
- 4.1. Did you know there is a chatbot that can be used to get information about Mensa?
- 4.2. Have you used MensaBot?
- 4.3. Is the information provider by MensaBot sufficient?
- 4.4. Is it easy to use?
- 4.5. Do you feel you can rely on the MensaBot information?
- 4.6. Is the information presented in a useful format?
- 4.7. Is the data provided by Mensabot up-to-date?

**Comment by Navidda** [comment]
### 1. General Information  
- 1.1.  Are you a student? (required)
- 1.2. Which one do you identify yourself (optional)?
	- Male
	- Female
- 1.3. Are you a vegetarian (or vegan)? (required)

### 2. Mensa in Corona Time
- 2.1. Have you used the Mensa during its to-go operation? (required)
- 2.2. If yes, were you satisfied with Mensa food during its to-go operation? (optional)
	- Not at all
	- to some extent
	- Fully satisfied
- 2.3. Are you happy that you can eat inside the Mensa again? (3 means indifferent) (required)
	- No all all
	- Indifferent
	- Completely
- 2.4. Do you think the COVID-19 protocols are observed in the Mensa? (required)
	- Completely Disagree
	- Partly agree
	- Completely Agree
- 2.5. If not, please give details. (optional)

### 3. Mensa Quality
- 3.1. How satisfied are you with the Mensa food? (required)
	- Very Unsatisfied, Very Satisfied
- 3.2. How satisfied are you with the value for money of the food you buy from Mensa? (required)
- 3.3. How satisfied are you with the process of buying your food from Mensa? (e.g waiting time in the queue, payment options, staff behavior, ...) (required)


### 4. MensaBot
- 4.1. Did you know there is a chatbot that can be used to get information about Mensa called MensaBot? (required)
- 4.2. Are you willing to use MensaBot? (required)

**Comment by lakhoune** [comment]
Can this issue be closed @Taeuber-hub ?
