### ISSUE TITLE
Develop branch: SQL Exception cannot create PoolableConnectionFactory

### ISSUE THREAD

**Issue by Taeuber-hub** [rwth-acis/mobsos-surveys#43]
![1](https://user-images.githubusercontent.com/73825173/147083677-cf551c62-34e8-4f8b-8c58-84267c6443b6.PNG)

Occurs when running locally due to an issue with the mysql dependency.

**Comment by lakhoune** [comment]
I think this issue should be fixed in the[ latest release](https://github.com/rwth-acis/mobsos-surveys/tree/0.4.0), where I updated the MySQL client
